/** Artisan Heritage — design tokens from Google Stitch (ripe_banana_yellow_update) */
export const colors = {
  background: "#fdf9f4",
  surface: "#fdf9f4",
  "surface-dim": "#ddd9d5",
  "surface-bright": "#fdf9f4",
  "surface-container-lowest": "#ffffff",
  "surface-container-low": "#f7f3ee",
  "surface-container": "#f1ede8",
  "surface-container-high": "#ebe8e3",
  "surface-container-highest": "#e6e2dd",
  "surface-variant": "#e6e2dd",
  "on-background": "#1c1c19",
  "on-surface": "#1c1c19",
  "on-surface-variant": "#504442",
  "inverse-surface": "#31302d",
  "inverse-on-surface": "#f4f0eb",
  outline: "#827472",
  "outline-variant": "#d3c3c0",
  "surface-tint": "#745853",
  primary: "#271310",
  "on-primary": "#ffffff",
  "primary-container": "#3e2723",
  "on-primary-container": "#ae8d87",
  "inverse-primary": "#e3beb8",
  "primary-fixed": "#ffdad4",
  "primary-fixed-dim": "#e3beb8",
  "on-primary-fixed": "#2b1613",
  "on-primary-fixed-variant": "#5b403c",
  secondary: "#1b6d24",
  "on-secondary": "#ffffff",
  "secondary-container": "#a0f399",
  "on-secondary-container": "#217128",
  "secondary-fixed": "#a3f69c",
  "secondary-fixed-dim": "#88d982",
  "on-secondary-fixed": "#002204",
  "on-secondary-fixed-variant": "#005312",
  tertiary: "#705d00",
  "on-tertiary": "#ffffff",
  "tertiary-container": "#c9a900",
  "on-tertiary-container": "#4c3f00",
  "tertiary-fixed": "#ffe16d",
  "tertiary-fixed-dim": "#e9c400",
  "on-tertiary-fixed": "#221b00",
  "on-tertiary-fixed-variant": "#544600",
  error: "#ba1a1a",
  "on-error": "#ffffff",
  "error-container": "#ffdad6",
  "on-error-container": "#93000a",
} as const;

export const spacing = {
  "max-width": "1280px",
  "margin-desktop": "64px",
  "margin-mobile": "20px",
  gutter: "24px",
  "section-gap": "40px",
  "container-padding-mobile": "24px",
  "container-padding-desktop": "48px",
} as const;

export const borderCard = "#E5E0D5";
